# main text of home
name: Fu Bihan
bio: A Girl who is now studying at 

# twitter summary info
description: A blog about Myself and some poems related

picture: assets/images/bihan.jpg

url: http://ddbohai.github.io/52mengmeng.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: myfacebook
twitter: mytwitter
github: mygithub
email: me@jane.doe

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
